[package]
name = "boids"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "./rust/lib.rs"

[profile.release]
lto = false

[dependencies]
wasm-bindgen = "0.2.67"
js-sys = "0.3.44"

[dependencies.web-sys]
version = "0.3.4"
features = ['CanvasRenderingContext2d']